# Generated by Django 4.2.11 on 2026-06-26 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('enrollment_number', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_enrollment_number', message='Enrollment number must be exactly 14 digits.', regex='^\\d{14}$')])),
                ('branch', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='Mobile number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
